### PR TITLE
fix macappstore URL

### PR DESCRIPTION
**Pull request by dhmoore**
The macappstore URL in update_app_path() should be macappstore://showUpdatesPage, at least for 10.11 and up.

### CODE REVIEW

**Comment by erikng** [comment]
Not for 10.14. This will need to be dynamically done per OS.

**Comment by erikng** [comment]
Actually maybe I'm wrong. Have you tested this on 10.11 through 10.14 and confirmed?

**Comment by dhmoore** [comment]
I've now tested macappstore://showUpdatesPage on 10.10 and up - it opens the App Store to the updates page. 
update_app_path() returns the SoftwareUpdate pref pane on 10.14.

**Comment by erikng** [comment]
Thanks! Merged

**Pull request merged**
