### PR TITLE
Launchagent changes

### PR DESCRIPTION
**Pull request by MScottBlake**

### CODE REVIEW

**Comment by erikng** [comment]
I disagree with the standard out change. That is a deliberate choice I made and why I used prints.

Please return that or I can't merge.

**Comment by MScottBlake** [comment]
Sure thing. It was a duplicated key and I just assumed that it was an oversight.

**Comment by MScottBlake** [comment]
Was it intentional to have the key in there twice? Should I remove the second one or do a straight up revert?

**Comment by erikng** [comment]
Oh weird it was duplicated?

**Comment by erikng** [comment]
Okay sorry you are correct. Merging now! Stupid mobile.

**Pull request merged**
