### PR TITLE
Handle updates from SUS

### PR DESCRIPTION
**Pull request by grahamgilbert**
This PR:

* Checks software update
* If the machine is configured to install updates in the background will open if there are updates that require a restart
* If it isn't, will open for any updates
* Will only open once a day
* Deletes the trackers when there aren't any updates to install

Still pending in a future PR:

* Clean up `main`. It's too long, so much needs to be split out.
* Handle individual force installs (if we care)

### CODE REVIEW

**Comment by erikng** [comment]
What happens if the min OS threshold passes but there are minor updates? I'm on mobile so perhaps not able to fully follow, but it seems that there may not be a case for that.

**Comment by grahamgilbert** [comment]
Line 450 handles that. The exit comes later if everything is dandy.

**Comment by erikng** [comment]
Okay yeah. I think this is fine then for a first pass but it definitely needs a refactor.

One thing we should do is if the major version is mismatched, don't even bother with the minor updates. This will speed up nudge considerably with this new stuff.

I'm going to merge this. Can you make sure you do that in your next PR?

**Comment by grahamgilbert** [comment]
Yes, if my offspring doesn’t arrive.   
  

  
  

  
  
>

**Pull request merged**
